config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'oauth2callback' => 'static_pages#set_google_drive_token'
  patch '/static_pages/home' => 'static_pages#home'
  post 'static/generator' => 'static_pages#generator'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
require "./lib/google_drive.rb"
require "./lib/pdf_converter.rb"

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :google_login, except: [:set_google_drive_token]

  def google_login
    unless $drive.get_credentials
      redirect_to('/oauth2callback')
    end
  end
end

app/controllers/static_pages_controller.rb
require 'open-uri'
require 'date'

class StaticPagesController < ApplicationController

  def set_google_drive_token
    if request['code'] == nil
      redirect_to($drive.authorization_url)
    else
      $drive.save_credentials(request['code'])
      redirect_to('/')
    end
  end

  def home
    sheet_id = "1qYyVQIio4wD_HvBHopC4Jcr8RyUjZ6ey9Maxqr-ZLw0"

    if params[:upload]

      #check to make sure only .pdf files were uploaded
      params[:upload].each do |file|
        if File.extname(file.path) != ".pdf"
          flash[:alert] = "You can only upload .PDF files"
          return redirect_to root_path
        end
      end

      all_names = []
      all_emails = []
      all_dates = []
      params[:upload].each_with_index do |file, index|
        read_file = File.read(file.tempfile)
        uploaded_file = File.open("uploaded_file_#{index}.pdf", "wb") { |file|
          file.write(read_file)
        }
        all_names.push(Array("#{params[:name]}"))
        all_emails.push(Array("#{params[:email]}"))
        all_dates.push(Array(Date.today.strftime("%Y-%m-%d")))
      end


      # convert each .pdf file to a .csv

      params[:upload].each_with_index do |file, index|
        final_file = File.basename("uploaded_file_#{index}.pdf")

        response = PageTextReceiver.new(params)
        params[:index] = "#{index}"
        response.run(final_file)
      end

      params[:upload].each_with_index do |file, index|
        file_append = File.read("response_#{index}.csv")
        File.open("finalized.csv", "a") do |file|
          file << file_append
        end
      end

      temp_sheet = $drive.create("finalized")

      all_pulled_values = []

      cell = true;
      first_val = 5
      second_val = 35

      while cell == true
        begin
          response = $drive.sheet_get_values("#{temp_sheet.id}", "B#{second_val}")
        rescue Google::Apis::ClientError => error
          cell = false;
          break
        end
        if response.values
          response = $drive.sheet_get_values("#{temp_sheet.id}", "B#{first_val}:B#{second_val}")
          all_pulled_values.push response.values
          first_val = second_val + 141
          second_val = first_val + 30
        else
          cell = false;
        end
      end

      (all_pulled_values.count).times do |index|
        all_pulled_values[index].map! { |i| i.join() }
      end

      # Checks to see where the next empty row is to place new content

      cell = true
      index_for_append = 2

      while cell == true
        begin
          first_empty_row = $drive.sheet_get_values("#{sheet_id}", "A#{index_for_append}")
        rescue Google::Apis::ClientError => error
          cell = false;
          break
        end
        if first_empty_row.values
          index_for_append += 1
        else
          cell = false;
        end
      end


      body = {"values": all_dates}

      $drive.sheet_append_values("#{sheet_id}", "A#{index_for_append}", body)

      body = {"values": all_names}

      $drive.sheet_append_values("#{sheet_id}", "B#{index_for_append}", body)

      body = {"values": all_emails}

      $drive.sheet_append_values("#{sheet_id}", "C#{index_for_append}", body)

      #######

      all_pulled_values.each_with_index do |array, i|
        body = {"values": [array]}
        $drive.sheet_append_values("#{sheet_id}", "D#{index_for_append}:AH#{index_for_append}", body)
        body = {"values": [[0, 0]]}
        $drive.sheet_append_values("#{sheet_id}", "AI#{index_for_append}:AJ#{index_for_append}", body)
        index_for_append += 1
      end

      #Delete the file so it's fresh for next run
      File.delete("finalized.csv")

      $drive.delete("#{temp_sheet.id}")

      params[:upload].each_with_index do |file, i|
        File.delete("response_#{i}.csv")
        File.delete("uploaded_file_#{i}.pdf")
      end


      flash[:notice] = "Thank You! Your Hexaco Results Were Submitted Successfully."
      redirect_to root_path
    end
  end

  def generator
    result = $drive.create("generator_base")
    result = $drive.get("#{result.id}")
    flash[:info] = "#{result.alternate_link}<br>#{result.id}"

    redirect_to root_path

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PdfConverter</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if flash[:notice] %>
        <div id="notice_wrapper">
          <p class="notice"><%= flash[:notice] %></p>
        </div>
      <% elsif alert %>
        <div id="notice_wrapper_alert">
          <p class="notice"><%= flash[:alert] %></p>
        </div>
      <% end %>
      <% if flash[:info] %>
      <div id="notice_wrapper_info">
        <p class="notice"><%= flash[:info].html_safe %></p>
      </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<% if session[:status_error] %>
<div class="status_error"><h3><%= session[:status_error] %></h3></div>
<% end %>

<% if session[:status_success] %>
<div class="status_success"><h3><%= session[:status_success] %></h3></div>
<% end %>

<div class="form">
  <!-- <%= link_to "Run New Sheet Generator", static_generator_path, method: :post, class: 'btn btn-success generator-btn' %> -->

  <%= form_tag "/static_pages/home", method: :patch, multipart: true do %>
    <label for="upload_" class="custom-file-upload">
        <span class="glyphicon glyphicon-download-alt"></span> Upload .PDF Files (ctrl+click for multi-select)
    </label>
    <%= file_field_tag "upload[]", multiple: true, accept: "application/pdf", required: true %><br>
    <%= text_field_tag :name, nil, placeholder: "Enter Your Name", class: 'form-control', pattern: ".*\\S.*[a-zA-z0-9 ]", required: true %><br>
    <%= text_field_tag :email, nil, placeholder: "Enter Your Email Address", class: 'form-control', pattern: ".*\\S.*[a-zA-z0-9 ]", required: true %><br>
    <!-- <%= text_field_tag :google_sheet_id, nil, placeholder: "Google Sheet ID", class: 'form-control', required: true %><br> -->
    <%= submit_tag "Convert and Import", class: 'btn btn-success form-control' %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>